### PR TITLE
Conditional logging

### PR DESCRIPTION
**Pull request by sascha-andres**
I am using this library to write a command line client. I wanted to turn off the logging lines without copying the code locally.

I added an `init` function which by default enables logging to preserve the old behavior and two functions to disable/enable logging

### CODE REVIEW

**Comment by sascha-andres** [comment]
Missed one log line, updated

**Comment by jason0x43** [comment]
Hah, I didn't know anyone was using this. I should probably port over some other updates I've made.

In any case, how about something a bit simpler, like just disabling or enabling the logger? Then you can avoid the need for an `init` and all the conditional wrappers.

```
func DisableLog() {
    logFlags = dlog.Flags()
    dlog.SetFlags(0)
    dlog.SetOutput(ioutil.Discard)
}

func EnableLog() {
    dlog.SetFlags(logFlags)
    dlog.SetOutput(os.StdErr)
}

**Comment by sascha-andres** [comment]
Looks better, was thinking about the conditionals and how to remove them. My solution would have been a wrapper but this is more elegant. I am updating my fork and test.

**Comment by sascha-andres** [comment]
Updated the code

**Comment by jason0x43** [comment]
Squashed and merged in 35d5d89d7381f4b8dcce627ec31c85309473f881. Thanks!

**Pull request closed without merging**
