### PR TITLE
Update Api & Report url

### PR DESCRIPTION
**Pull request by Domonlee**

### CODE REVIEW

**Comment by Domonlee** [comment]
I check those two PRs :

- https://github.com/toggl/toggl_api_docs/pull/382
- https://github.com/toggl/toggl_api_docs/pull/385

commit the new url with official docs. 
And yesterday, seems like toggl restored the old API urls. But I have no idea how long the old api url will exist.

**Comment by Leland** [comment]
@jason0x43 ping on this one, they'll be deprecating the current URLs at some point this year: https://toggl.com/blog/api-documentation-change

This will close #58, btw.

**Comment by rogatty** [comment]
I just got this email:
> Hi there,
>
>We are reaching out because we detected API usage coming from your Toggl Track account using the www.toggl.com (or toggl.com) domain.
>
>After last year's rebranding, we released api.track.toggl.com as our new domain for API usage. These changes were communicated via newsletter and the following blog post. The API Docs were also updated to reflect the domain changes.
>
>We want to inform you that the usage of www.toggl.com (or toggl.com) domain for the API will be dropped after 'June 30th 2021'.
>
>We encourage you to perform the switch to api.track.toggl.com as soon as possible in order to prevent disruption.
>
>Best wishes,
The Toggl Track Team
support@track.toggl.com

**Comment by jason0x43** [comment]
Thanks for the reminder!

**Pull request merged**
